name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build y Correr contenedor MySQL
        run: |
          docker build -t mydb ./database
          docker run -d --name mydb -p 3306:3306 --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 mydb
        working-directory: .

      - name: Esperar que MySQL sea healthy
        run: |
          until docker inspect -f "{{.State.Health.Status}}" mydb | grep -q "healthy"; do
            sleep 5
          done

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependencias
        run: npm install
        working-directory: ./backend

      - name: Correr Tests
        run: |
          (timeout 10 npx mocha || true)
          if [ "$(timeout 10 npx mocha | grep -c '5 passing')" -eq 1 ]; then
            echo "Tests pasaron exitosamente."
          else
            echo "Los tests no pasaron. Terminando el flujo de trabajo."
            exit 1
          fi
        working-directory: ./backend

      - name: Correr backend
        run: nohup node app.js &    # Ejecuta la aplicación en segundo plano
        working-directory: ./backend

      - name: Correr frontend
        run: |
          npm install
          nohup npm start &
        working-directory: ./frontend

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t my-frontend ./frontend
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-frontend ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
        working-directory: .

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t my-backend ./backend
          docker tag my-backend ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
        working-directory: .

      - name: Build and Push Database Docker Image
        run: |
          docker build -t mydb ./database
          docker tag mydb ${{ secrets.DOCKERHUB_USERNAME }}/mydb:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydb:latest
        working-directory: .
