name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          cd backend
          docker build -t $DOCKERHUB_USERNAME/backend:latest .
          docker push $DOCKERHUB_USERNAME/backend:latest
          cd ../frontend
          docker build -t $DOCKERHUB_USERNAME/frontend:latest .
          docker push $DOCKERHUB_USERNAME/frontend:latest
          cd ../database
          docker build -t $DOCKERHUB_USERNAME/database:latest .
          docker push $DOCKERHUB_USERNAME/database:latest

      - name: Configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: tateti-404421

      - name: Deploy Frontend
        run: |
          gcloud run deploy frontend \
            --image=docker.io/piterfmz/frontend:latest \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated

      - name: Deploy Backend
        run: |
          gcloud run deploy backend \
            --image=docker.io/piterfmz/backend:latest \
            --add-cloudsql-instances tateti-404421:us-central1:prueba \
            --update-env-vars INSTANCE_CONNECTION_NAME=tateti-404421:us-central1:prueba,DB_PASS=pedro123,DB_USER=root,DB_NAME=perros \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated
