name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build y Correr contenedor MySQL
        run: |
          docker build -t mydb ./database
          docker run -d --name mydb -p 3306:3306 --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 mydb
        working-directory: .

      - name: Esperar que MySQL sea healthy
        run: |
          until docker inspect -f "{{.State.Health.Status}}" mydb | grep -q "healthy"; do
            sleep 5
          done

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependencias
        run: npm install
        working-directory: ./backend

      - name: Correr Tests
        run: nohup npx mocha &
        working-directory: ./backend

      - name: Verificar resultados de las pruebas
        run: |
          sleep 60  # Espera un tiempo para que las pruebas se ejecuten

          test_result=$(tail -n 10 nohup.out)
          echo "$test_result"
          if [[ "$test_result" == *"5 passing"* ]]; then
            echo "Las pruebas pasaron exitosamente."
          else
            echo "Las pruebas no pasaron como se esperaba. Terminando el flujo de trabajo."
            exit 1
          fi
        working-directory: ./backend

      - name: Correr backend
        run: nohup node app.js &    # Ejecuta la aplicación en segundo plano
        working-directory: ./backend
