name: Tests Unitarios

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build y Correr contenedor MySQL
        run: |
          docker build -t mydb ./database
          docker run -d --name mydb -p 3306:3306 --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 mydb
        working-directory: .

      - name: Esperar que MySQL sea healthy
        run: |
          until docker inspect -f "{{.State.Health.Status}}" mydb | grep -q "healthy"; do
            sleep 5
          done

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependencias
        run: npm install
        working-directory: ./backend

      - name: Correr Tests
        run: |
          (timeout 10 "NODE_ENV=local npx mocha" || true)
          if [ "$(timeout 10 "NODE_ENV=local npx mocha" | grep -c '5 passing')" -eq 1 ]; then
            echo "Tests pasaron exitosamente."
          else
            echo "Los tests no pasaron. Terminando el flujo de trabajo."
            exit 1
          fi
        working-directory: ./backend

      - name: Correr backend
        run: nohup NODE_ENV=local node app.js &    # Ejecuta la aplicación en segundo plano
        working-directory: ./backend

      - name: Correr frontend
        run: |
          npm install
          nohup npm start &
        working-directory: ./frontend
